// MATCH: image=rev22 addr=0x0C7D len=74 func=rev22_vecint_dispatch_table
/* GENERATED by tools/gen_data_blocks.py -- do not hand-edit the
 * bytes; regenerate instead. Transcribed from the stock image so
 * they cannot be mistyped, and proved by the byte match.
 *
 * The USB interrupt dispatch table. The single functional difference
 * between the two firmwares lives in entry 20 (SOF): Rev 20 points it
 * at a one-byte RET stub, Rev 22 at its playback-DMA watchdog.
 *
 * Emitted from a __naked function so the bytes land in this
 * candidate's code segment, which link51 places at the stock
 * address like any other candidate. */
void rev22_vecint_dispatch_table(void) __naked {
    __asm
        ; 37 entries, two bytes each, indexed by the VECINT value
        ; DIRECTLY (not value/2). Each is the address the USB
        ; interrupt dispatcher jumps to for that source.
        .db 0x0C, 0xC7    ; [ 0] OEP0        -> 0x0CC7
        .db 0x00, 0x10    ; [ 1] OEP1        -> 0x0010
        .db 0x00, 0x11    ; [ 2] OEP2        -> 0x0011
        .db 0x00, 0x12    ; [ 3] OEP3        -> 0x0012
        .db 0x00, 0x16    ; [ 4] OEP4        -> 0x0016
        .db 0x00, 0x17    ; [ 5] OEP5        -> 0x0017
        .db 0x00, 0x18    ; [ 6] OEP6        -> 0x0018
        .db 0x00, 0x19    ; [ 7] OEP7        -> 0x0019
        .db 0x0F, 0x91    ; [ 8] IEP0        -> 0x0F91
        .db 0x00, 0x1A    ; [ 9] IEP1        -> 0x001A
        .db 0x00, 0x1E    ; [10] IEP2        -> 0x001E
        .db 0x00, 0x1F    ; [11] IEP3        -> 0x001F
        .db 0x00, 0x20    ; [12] IEP4        -> 0x0020
        .db 0x00, 0x21    ; [13] IEP5        -> 0x0021
        .db 0x00, 0x22    ; [14] IEP6        -> 0x0022
        .db 0x10, 0x29    ; [15] IEP7        -> 0x1029
        .db 0x10, 0x2A    ; [16] STPOW       -> 0x102A
        .db 0x10, 0x35    ; [17] (reserved)  -> 0x1035
        .db 0x00, 0x26    ; [18] SETUP       -> 0x0026
        .db 0x10, 0x2B    ; [19] PSOF        -> 0x102B
        .db 0x0D, 0x58    ; [20] SOF         -> 0x0D58
        .db 0x10, 0x2C    ; [21] RESR        -> 0x102C
        .db 0x00, 0x06    ; [22] SUSR        -> 0x0006
        .db 0x0F, 0x64    ; [23] RSTR        -> 0x0F64
        .db 0x10, 0x2D    ; [24] CPRX        -> 0x102D
        .db 0x10, 0x2E    ; [25] CPTX        -> 0x102E
        .db 0x10, 0x35    ; [26] DPRX        -> 0x1035
        .db 0x10, 0x35    ; [27] DPTX        -> 0x1035
        .db 0x10, 0x2F    ; [28] I2CRX       -> 0x102F
        .db 0x10, 0x30    ; [29] I2CTX       -> 0x1030
        .db 0x10, 0x35    ; [30] (reserved)  -> 0x1035
        .db 0x10, 0x31    ; [31] XINT        -> 0x1031
        .db 0x10, 0x32    ; [32] (undefined) -> 0x1032
        .db 0x10, 0x33    ; [33] (undefined) -> 0x1033
        .db 0x10, 0x35    ; [34] (undefined) -> 0x1035
        .db 0x10, 0x35    ; [35] (undefined) -> 0x1035
        .db 0x10, 0x34    ; [36] NO_INT      -> 0x1034
    __endasm;
}
