// MATCH: image=rev22 addr=0x0FBA len=40 func=rev22_c51_initseg_table
/* GENERATED by tools/gen_data_blocks.py -- do not hand-edit the
 * bytes; regenerate instead. Transcribed from the stock image so
 * they cannot be mistyped, and proved by the byte match.
 *
 * Keil's C51 startup initialiser table, interpreted by the runtime at
 * boot to zero IRAM locations. Identical content in both images.
 *
 * Emitted from a __naked function so the bytes land in this
 * candidate's code segment, which link51 places at the stock
 * address like any other candidate. */
void rev22_c51_initseg_table(void) __naked {
    __asm
        ; Keil ?C_INITSEG: three-byte records, count then the
        ; IRAM address to clear, terminated by a zero count.
        .db 0x01, 0x22, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x20, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x25, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x23, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x24, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x21, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x09, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x0C, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x0B, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x0E, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x0A, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x0D, 0x00    ; clear 1 byte(s) at IRAM 0x00
        .db 0x01, 0x08, 0x03    ; clear 1 byte(s) at IRAM 0x03
        .db 0x00    ; terminator
    __endasm;
}
