// MATCH: image=rev20 addr=0x0C93 len=74 func=vecint_dispatch_table
/* GENERATED by tools/gen_data_blocks.py -- do not hand-edit the
 * bytes; regenerate instead. Transcribed from the stock image so
 * they cannot be mistyped, and proved by the byte match.
 *
 * The USB interrupt dispatch table. The single functional difference
 * between the two firmwares lives in entry 20 (SOF): Rev 20 points it
 * at a one-byte RET stub, Rev 22 at its playback-DMA watchdog.
 *
 * Emitted from a __naked function so the bytes land in this
 * candidate's code segment, which link51 places at the stock
 * address like any other candidate. */
void vecint_dispatch_table(void) __naked {
    __asm
        ; 37 entries, two bytes each, indexed by the VECINT value
        ; DIRECTLY (not value/2). Each is the address the USB
        ; interrupt dispatcher jumps to for that source.
        .db 0x0D, 0x25    ; [ 0] OEP0        -> 0x0D25
        .db 0x00, 0x10    ; [ 1] OEP1        -> 0x0010
        .db 0x00, 0x11    ; [ 2] OEP2        -> 0x0011
        .db 0x00, 0x12    ; [ 3] OEP3        -> 0x0012
        .db 0x00, 0x16    ; [ 4] OEP4        -> 0x0016
        .db 0x00, 0x17    ; [ 5] OEP5        -> 0x0017
        .db 0x00, 0x18    ; [ 6] OEP6        -> 0x0018
        .db 0x00, 0x19    ; [ 7] OEP7        -> 0x0019
        .db 0x0F, 0xC4    ; [ 8] IEP0        -> 0x0FC4
        .db 0x00, 0x1A    ; [ 9] IEP1        -> 0x001A
        .db 0x00, 0x1E    ; [10] IEP2        -> 0x001E
        .db 0x00, 0x1F    ; [11] IEP3        -> 0x001F
        .db 0x00, 0x20    ; [12] IEP4        -> 0x0020
        .db 0x00, 0x21    ; [13] IEP5        -> 0x0021
        .db 0x00, 0x22    ; [14] IEP6        -> 0x0022
        .db 0x10, 0x31    ; [15] IEP7        -> 0x1031
        .db 0x10, 0x32    ; [16] STPOW       -> 0x1032
        .db 0x10, 0x3E    ; [17] (reserved)  -> 0x103E
        .db 0x00, 0x26    ; [18] SETUP       -> 0x0026
        .db 0x10, 0x33    ; [19] PSOF        -> 0x1033
        .db 0x10, 0x34    ; [20] SOF         -> 0x1034
        .db 0x10, 0x35    ; [21] RESR        -> 0x1035
        .db 0x00, 0x06    ; [22] SUSR        -> 0x0006
        .db 0x0F, 0x43    ; [23] RSTR        -> 0x0F43
        .db 0x10, 0x36    ; [24] CPRX        -> 0x1036
        .db 0x10, 0x37    ; [25] CPTX        -> 0x1037
        .db 0x10, 0x3E    ; [26] DPRX        -> 0x103E
        .db 0x10, 0x3E    ; [27] DPTX        -> 0x103E
        .db 0x10, 0x38    ; [28] I2CRX       -> 0x1038
        .db 0x10, 0x39    ; [29] I2CTX       -> 0x1039
        .db 0x10, 0x3E    ; [30] (reserved)  -> 0x103E
        .db 0x10, 0x3A    ; [31] XINT        -> 0x103A
        .db 0x10, 0x3B    ; [32] (undefined) -> 0x103B
        .db 0x10, 0x3C    ; [33] (undefined) -> 0x103C
        .db 0x10, 0x3E    ; [34] (undefined) -> 0x103E
        .db 0x10, 0x3E    ; [35] (undefined) -> 0x103E
        .db 0x10, 0x3D    ; [36] NO_INT      -> 0x103D
    __endasm;
}
