#!/usr/bin/env python3
"""Fail if the declared endpoint set changed without its manifest being updated.

WHY THIS EXISTS -- #214, and it is worth stating precisely because the bug was
not a reasoning error.

#188 made SET_FEATURE stall every selector, and justified ENDPOINT_HALT with a
comment enumerating our endpoints: "the streaming endpoints are isochronous and
have no halt". That was TRUE when written. The device then had EP0 and three
isochronous endpoints, and 9.4.5 requires halt only of interrupt and bulk, so
every one of them was genuinely outside it.

Then #207 added EP 0x83, an INTERRUPT endpoint, and the premise silently stopped
holding. Interrupt endpoints are not exempt: 9.4.9 makes halt mandatory there.
Nothing re-derived the conclusion, because nothing connected "we added an
endpoint" to "a comment in the feature handler enumerates our endpoint types".
It shipped, and ch9_probe --invasive found it later.

That is a CORRECT INFERENCE LEFT STANDING AFTER ITS INPUTS CHANGED, which no
amount of care at the point of change would have caught -- the person adding an
endpoint has no reason to read the feature dispatcher. It needs a mechanical
link, which is what this is: the endpoint set is a manifest, changing it fails
the build, and the manifest tells you what to re-check.

Modelled on tools/sfr_writes.allowed, which exists for the same shape of
problem: a diff you must look at, not a rule you must remember.

    python3 tools/check_endpoint_manifest.py [--update]
"""
import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from verify_descriptors import load_ihx, load_symbols, slice_mem  # noqa: E402

DT_ENDPOINT = 0x05
XFER = {0: "control", 1: "isochronous", 2: "bulk", 3: "interrupt"}

MANIFEST = Path(__file__).resolve().parent / "endpoints.allowed"

HEADER = """\
# Declared endpoint manifest -- regenerated by check_endpoint_manifest.py --update.
#
# Every line: ADDR  TYPE  wMaxPacketSize
#
# A DIFF HERE IS NOT A FORMALITY. The endpoint set is load-bearing for code that
# lives nowhere near the descriptors, and #214 shipped because one such place
# went stale silently. Before re-baselining, re-read each of these:
#
#   * usb.c REQ_SET_FEATURE / REQ_CLEAR_FEATURE -- ENDPOINT_HALT is MANDATORY on
#     interrupt and bulk endpoints -- 9.4.5 says the Halt feature 'is required
#     to be implemented for all interrupt and bulk endpoint types', which is
#     what leaves isochronous ones out. Adding a non-iso endpoint means
#     implementing halt for it.
#   * usb.c REQ_GET_STATUS -- 9.4.5 requires the halt bit to read back for any
#     endpoint that has the feature.
#   * regs.h endpoint buffer map -- EP_BBAX/EP_BSIZE work in 8-byte units and
#     the region is 0xFA10-0xFF27, with the setup packet buffer at 0xFF28.
#     IEPBSIZx sizes the X/Y PAIR, not one buffer (#207).
#   * the UAC1 descriptor bundle -- an audio endpoint descriptor is 9 bytes, not
#     7: bRefresh and bSynchAddress are not optional.
"""


def endpoints_from_image(ihx, mapfile):
    mem = load_ihx(ihx)
    syms = load_symbols(mapfile)
    if "_AppConfigDesc" not in syms:
        sys.exit("no _AppConfigDesc in the map -- build first")
    base = syms["_AppConfigDesc"]
    head = slice_mem(mem, base, 4)
    cfg = slice_mem(mem, base, head[2] | (head[3] << 8))

    out, p = [], 0
    while p + 1 < len(cfg):
        blen, btype = cfg[p], cfg[p + 1]
        if blen == 0:
            break
        if btype == DT_ENDPOINT and p + 6 < len(cfg):
            addr, attr = cfg[p + 2], cfg[p + 3]
            mps = cfg[p + 4] | (cfg[p + 5] << 8)
            out.append((addr, XFER.get(attr & 3, "?"), mps))
        p += blen
    # An endpoint appearing in several altsettings is one endpoint.
    return sorted(set(out))


def fmt(eps):
    return "".join("0x%02X  %-12s %d\n" % e for e in eps)


def load_manifest():
    if not MANIFEST.exists():
        return None
    out = []
    for line in MANIFEST.read_text().splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        a, t, m = line.split()
        out.append((int(a, 16), t, int(m)))
    return sorted(set(out))


def main():
    ap = argparse.ArgumentParser()
    here = Path(__file__).resolve().parent.parent
    ap.add_argument("--ihx", default=str(here / "mboxfw/build/mboxfw.ihx"))
    ap.add_argument("--map", default=str(here / "mboxfw/build/mboxfw.map"))
    ap.add_argument("--update", action="store_true")
    a = ap.parse_args()

    if not os.path.exists(a.ihx) or not os.path.exists(a.map):
        print("build artifacts missing -- run make first", file=sys.stderr)
        return 2

    live = endpoints_from_image(a.ihx, a.map)

    if a.update:
        MANIFEST.write_text(HEADER + "\n" + fmt(live))
        print("endpoints.allowed updated:\n" + fmt(live))
        return 0

    known = load_manifest()
    if known is None:
        print("no endpoints.allowed -- create it with --update", file=sys.stderr)
        return 1

    added = [e for e in live if e not in known]
    gone = [e for e in known if e not in live]
    if not added and not gone:
        print("ENDPOINT MANIFEST PASS: %d endpoints, all match" % len(live))
        return 0

    print("ENDPOINT MANIFEST FAIL:")
    for e in added:
        print("  + 0x%02X %s %dB  -- NEW" % e)
        if e[1] in ("interrupt", "bulk"):
            print("      %s endpoints are NOT exempt from ENDPOINT_HALT "
                  "(§9.4.5 requires it of interrupt and bulk only)." % e[1])
            print("      §9.4.9 set, §9.4.1 clear, §9.4.5 report -- all "
                  "mandatory. This is exactly #214.")
    for e in gone:
        print("  - 0x%02X %s %dB  -- REMOVED" % e)
    print("\nRe-read the sites listed in endpoints.allowed, then re-baseline:")
    print("    python3 tools/check_endpoint_manifest.py --update")
    return 1


if __name__ == "__main__":
    sys.exit(main())
