"""Leading exact-zero run at the top of a capture, reported in FRAMES.

The point of frames rather than milliseconds: the AK5383 specifies tRTV (RST
rising -> valid SDATA) as 8960/fs and tRCF (calibration) as 8704/fs -- fixed
SAMPLE counts, not fixed times. If the leading silence is the same number of
FRAMES at 48000 and 44100 it is generated by a counter clocked at fs inside the
part; if it is the same number of MILLISECONDS it is not.
"""
import sys, wave
import numpy as np

for path in sys.argv[1:]:
    w = wave.open(path, "rb")
    fs, nch, sw = w.getframerate(), w.getnchannels(), w.getsampwidth()
    n = w.getnframes()
    raw = w.readframes(n)
    w.close()
    a = np.frombuffer(raw, dtype=np.uint8).reshape(n, nch * sw).astype(np.int32)

    def ch(o):
        v = a[:, o] | (a[:, o + 1] << 8) | (a[:, o + 2] << 16)
        return np.where(v & 0x800000, v - (1 << 24), v)

    # Both channels: one bit gates the whole capture path, so a run on a single
    # channel would mean something other than the gate.
    z = (ch(0) == 0) & (ch(sw) == 0)
    lead = int(np.argmax(~z)) if not z.all() else n
    rest = ch(0)[lead:].astype(np.float64) / 8388608.0
    rms = 20 * np.log10(max(np.sqrt(np.mean(rest ** 2)), 1e-12)) if rest.size else float("nan")
    print("%-22s fs=%6d  n=%7d  LEAD ZEROS = %6d frames = %7.2f ms   after: %7.1f dBFS  dc=%+.5f"
          % (path.split("/")[-1], fs, n, lead, 1000.0 * lead / fs, rms,
             float(np.mean(rest)) if rest.size else float("nan")))
