#!/usr/bin/env python3
"""
Generate ramflash/src/payload.c from a raw EEPROM image.

WHY THIS EXISTS. ramflash/src/payload.c carried the header "GENERATED by the
payload step in ramflash/README.md — do not edit". That README does not exist.
On 2026-08-03, with Mbox A down and an SDA short the only way back in, the
recovery image turned out to contain 4637 bytes of an unidentified mboxfw
build that matched neither stock revision, produced by a process nobody could
re-run. This script is that missing step, written down.

WHAT fw_image[] HAS TO BE. ramflash/src/main.c writes fw_image[off] to EEPROM
offset off for off in [HEADER_SIZE, fw_len), then the header body, then the
signatures, then the checksum last. So fw_image is a RAW EEPROM image —
18-byte header followed by code — not the record-stream .bin the DFU flasher
consumes. rev20_eeprom.bin is already in that form.

TRUNCATION. Stock Rev 20's EEPROM region is 8192 bytes but its last non-0xFF
byte is at 0x103E: 4159 bytes of real content, the rest FF fill. We emit only
the real content and rewrite payloadSize to match, because:

  - ramflash's own code plus the payload must fit in 6016 bytes of program
    RAM. Full-length would be ~8685 and could not exist on the part. This is
    the same limit that bricked Mbox A; see BRICK_LOG.md flash #3.
  - every emitted byte is one 24C64 program cycle, and the write already
    takes minutes.

Truncating means rewriting two header fields:

  offset 16-17  payloadSize, BIG-endian, = len(image) - 18
  offset 0      checksum, = sum(header[1..17]) & 0xFF
                (Eeprom.c eepromCheckFirmware, "computed by adding bytes";
                 the rule is also stated in mboxfw/src/eeprom.c)

Usage:
    python3 tools/ramflash_payload.py firmware_stock/rev20_eeprom.bin
    python3 tools/ramflash_payload.py <img> -o ramflash/src/payload.c
    python3 tools/ramflash_payload.py <img> --check      # verify, write nothing
"""

import argparse
import sys
from pathlib import Path

HEADER_SIZE = 18
CHKSUM_OFF = 0
PAYLOAD_SIZE_OFF = 16      # big-endian, 2 bytes
PROGRAM_RAM = 6016         # TAS1020B datasheet; see tools/check_code_size.py


def real_extent(code: bytes) -> int:
    """Length of the code region up to and including its last non-0xFF byte."""
    for i in range(len(code) - 1, -1, -1):
        if code[i] != 0xFF:
            return i + 1
    return 0


def build_image(raw: bytes):
    if len(raw) < HEADER_SIZE:
        raise SystemExit(f"image is only {len(raw)} bytes, shorter than a header")
    header = bytearray(raw[:HEADER_SIZE])
    code = raw[HEADER_SIZE:]
    n = real_extent(code)
    if n == 0:
        raise SystemExit("code region is entirely 0xFF — refusing to emit it")

    header[PAYLOAD_SIZE_OFF] = (n >> 8) & 0xFF
    header[PAYLOAD_SIZE_OFF + 1] = n & 0xFF
    header[CHKSUM_OFF] = sum(header[1:HEADER_SIZE]) & 0xFF
    return bytes(header) + code[:n]


def emit_c(img: bytes, src: Path) -> str:
    rows = []
    for i in range(0, len(img), 12):
        rows.append("    " + " ".join("0x%02x," % b for b in img[i:i + 12]))
    return (
        "/* GENERATED by tools/ramflash_payload.py — do not edit.\n"
        " *\n"
        " * Source image: %s\n"
        " * Raw EEPROM form: %d-byte header + %d bytes of code.\n"
        " * payloadSize and checksum rewritten for the truncated length;\n"
        " * regenerate rather than hand-editing either.\n"
        " */\n"
        "#include \"payload.h\"\n"
        "\n"
        "const unsigned int fw_len = %du;\n"
        "const __code unsigned char fw_image[%d] = {\n%s\n};\n"
        % (src, HEADER_SIZE, len(img) - HEADER_SIZE, len(img), len(img),
           "\n".join(rows))
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("image", help="raw EEPROM image (header first), e.g. "
                                  "firmware_stock/rev20_eeprom.bin")
    ap.add_argument("-o", "--output", default="ramflash/src/payload.c")
    ap.add_argument("--check", action="store_true",
                    help="report and verify, write nothing")
    args = ap.parse_args()

    src = Path(args.image)
    raw = src.read_bytes()
    img = build_image(raw)

    hdr = img[:HEADER_SIZE]
    stated = (hdr[PAYLOAD_SIZE_OFF] << 8) | hdr[PAYLOAD_SIZE_OFF + 1]
    print(f"  source            {src} ({len(raw)} bytes)")
    print(f"  header            {' '.join('%02x' % b for b in hdr)}")
    print(f"  code emitted      {len(img) - HEADER_SIZE} bytes "
          f"(was {len(raw) - HEADER_SIZE}, trailing 0xFF dropped)")
    print(f"  payloadSize field {stated}")
    print(f"  checksum          0x{hdr[CHKSUM_OFF]:02X}")

    fails = []
    if stated != len(img) - HEADER_SIZE:
        fails.append("payloadSize field does not match the emitted length")
    if (sum(hdr[1:HEADER_SIZE]) & 0xFF) != hdr[CHKSUM_OFF]:
        fails.append("header checksum does not satisfy "
                     "sum(header[1..17]) & 0xFF == header[0]")
    # The payload rides inside ramflash's own image, so it competes for the
    # same 6016 bytes. Leave room for ramflash's logic; the build is the real
    # check but a clear message here beats an ?ASlink error.
    if len(img) >= PROGRAM_RAM:
        fails.append(f"payload alone is {len(img)} bytes against "
                     f"{PROGRAM_RAM} of program RAM — cannot fit with "
                     f"ramflash's own code")
    # Every byte is a 24C64 program cycle.
    print(f"  program cycles    {len(img)} "
          f"(the write takes minutes — do not interrupt it)")

    if fails:
        print("\nFAIL:")
        for f in fails:
            print("  - " + f)
        return 1

    if args.check:
        print("\nCHECK PASS: nothing written.")
        return 0

    out = Path(args.output)
    out.write_text(emit_c(img, src))
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
